### PR TITLE
"Experiencing Lag?" fixed

### PR DESCRIPTION
**Pull request by MrScopes**

### CODE REVIEW

**Review by jellz — CHANGES_REQUESTED** [review]
- Make "ip" uppercase
- play.warzone.network isn't an IP address 🤔

**Comment by BennyDoesStuff** [comment]
play.warzone.network is an IP address, seems to work fine for me. Not sure why it doesn't work for some people though.

**Comment by MrScopes** [comment]
> play.warzone.network is an IP address, seems to work fine for me. Not sure why it doesn't work for some people though.

same I use it, but I think he was referring to it saying `play.warzone.network` and not `149.56.13.64`

**Comment by jellz** [comment]
Yeah I meant that domain isn't an IP address... However this PR is good and it should be merged 👍

**Pull request closed without merging**
